### ISSUE TITLE
func Init accepts unused param

### ISSUE THREAD

**Issue by sounak98** [efectn/fx-zerolog#2]
Currently function `Init` accepts an unused parameter `logger zerolog.Logger`.

The updated `Init` should ideally look something like this.

```go
func Init() func(logger zerolog.Logger) fxevent.Logger {
	return func(logger zerolog.Logger) fxevent.Logger {
		return &ZeroLogger{Logger: logger}
	}
}
```

There should also probably be another variant of the `Init` function which can be used when the logger constructor returns a `*zerolog.Logger` instead of `zerolog.Logger`.

```go
func InitPtr() func(logger *zerolog.Logger) fxevent.Logger {
	return func(logger *zerolog.Logger) fxevent.Logger {
		return &ZeroLogger{Logger: *logger}
	}
}
```

Should I go ahead and add a PR for these changes?

**Comment by efectn** [comment]
You're right but we can make something else instead of removing it.

https://github.com/efectn/fx-zerolog/blob/main/zerolog.go#L16
https://github.com/efectn/fx-zerolog/blob/main/zerolog.go#L18

If we change the name of param, we should be able to use custom logger instances. Can you test it? Also you can create PR for these. InitPtr sounds nice.

**Comment by efectn** [comment]
@sounak98

**Comment by sounak98** [comment]
> If we change the name of param, we should be able to use custom logger instances.

@efectn is there any good reason for using a custom logger instance? In all cases we would want the injected logger dependency right?
